services:
  music-library-downloader:
    image: music-library-downloader
    build:
      context: .
      dockerfile: ./Containerfile
    env_file:
      - .env
    command: ["uv", "run", "main.py"]
    volumes:
      - ./auto-downloaded-songs:/app/auto-downloaded-songs
      - ./logs:/app/logs
